const host = 'http://localhost:3001'
export const intervaloConfianzaPoblacionDesconocida = `${host}/intervaloConfianzaPoblacionDesconocida`
export const intervaloConfianzaPoblacionConocidaVarianzaConocida = `${host}/intervaloConfianzaPoblacionConocidaVarianzaConocida`
export const intervaloMediaPoblacionNormalVarianzaDesconocidaMuestraPeque = `${host}/intervaloMediaPoblacionNormalVarianzaDesconocidaMuestraPeque`
export const intervaloMediaPoblacionDesconocidaMuestraGrande = `${host}/intervaloMediaPoblacionDesconocidaMuestraGrande`
export const intervaloProporcionMuestraGrande = `${host}/intervaloProporcionMuestraGrande`
export const intervaloDiferenciaProporcionMuestraGrande = `${host}/intervaloDiferenciaProporcionMuestraGrande`
export const intervaloDiferenciaMediaVarianzaConocidaMuestraGrande = `${host}/intervaloDiferenciaMediaVarianzaConocidaMuestraGrande`
export const intervaloDiferenciaMediaVarianzaDesconocidaIgualesMuestraPequeña = `${host}/intervaloDiferenciaMediaVarianzadesconocidaIgualesMuestraPeque`
export const intervaloDiferenciaMediaVarianzaDesconocidaDiferentesMuestraPequeña = `${host}/intervaloDiferenciaMediaVarianzadesconocidaDiferentesMuestraPeque`
export const intervaloVarianzaPoblacionNormal = `${host}/intervaloVarianzaPoblacionNormal`
export const intervaloRazonVarianzas = `${host}/intervaloRazonVarianzas`
